# SPDX-License-Identifier: GPL-2.0-only

CONFIG_BUILD_VENDORSI := true

LINUXINCLUDE    +=  -I$(srctree)/techpack/eva/include \
                    -I$(srctree)/techpack/eva/include/uapi \
                    -I$(srctree)/techpack/eva/include/uapi/eva

# auto-detect subdirs
obj-y +=msm/
